### ISSUE TITLE
Type 'Optional<Wrapped>' does not conform to protocol 'AnyArrayOrSet'

### ISSUE THREAD

**Issue by joel-perry** [ftchirou/PredicateKit#4]
PredicateKit fails to build in Xcode 12.5 beta, with the following error in Predicate.swift at line 622:

Type 'Optional<Wrapped>' does not conform to protocol 'AnyArrayOrSet'

**Comment by ftchirou** [comment]
Thanks for reporting this. I'll look into it.

**Comment by ftchirou** [comment]
Fixed in [`1.3.0`](https://github.com/ftchirou/PredicateKit/releases/tag/1.3.0).
