### ISSUE TITLE
Question on related blog post: Designing modern data access layers in Swift

### ISSUE THREAD

**Issue by jessegrosjean** [ftchirou/PredicateKit#7]
I'm trying to work through your blog post (thanks, learning a lot):

- https://faical.dev/articles/modern-swift-data-access-layers.html

I'm getting stuck on compile error for this code:

```swift
extension Predicate {
    func isIncluded() -> (T) -> Bool {
        switch self {
        case let .comparison(keyPath, .greaterThan, value):
            return { $0[keyPath: keyPath] > value } // error!!!
...
```

I am getting error:

```
Binary operator '>' cannot be applied to operands of type 'Any' and 'Primitive'
```

Any idea why this is happening or how I could work around it?

Thanks,
Jesse

**Comment by ftchirou** [comment]
Hi @jessegrosjean! You need custom comparison operators between `Any` and `Primitive` to get rid of the errors. I used [this implementation](https://gist.github.com/ftchirou/c9b5b454a532c14e9320f28cfbea2eee) for the article.
